image: node

cache:
  paths:
    - node_modules/

before_script:
  - apt-get update -qq
  - apt-get install -qq git
  - "which ssh-agent || ( apt-get install -qq openssh-client )"
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy:
  stage: deploy
  environment:
    name: staging
    url: https://das-grosse-public.herokuapp.com/
  script:
    # - bash deploy/deploy.sh
    # for deployment to heroku
    # - npm install dpl
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/das-grosse-public.git HEAD:master
    - echo "Deployed to staging server"
  only:
    - staging